### ISSUE TITLE
Not able to know if the script has stopped

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#141]
I am not able to know if the script has stopped. I don't see any note IDs either.
If there is some error, it must show some error right or it will just kee running? I mean is there a check for run times?

**Comment by Pseudonium** [comment]
Check the console to see if there was an uncaught error - I just fixed one, new version

**Comment by dummifiedme** [comment]
Where shall I find the console?
Also, the IDs are still not visible. And notes aren't exporting into ANKI :(
