### ISSUE TITLE
Anki sync paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by QuantumCat3141** [Pseudonium/Obsidian_to_Anki#428]
When clicking Scan Vault for the first time, "Checking connection to Anki..." appears in console. 

![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/50957670/17b05a25-3d08-4f82-a6df-e7ca702ec9a1)

The connection to Anki is successful, but after some time,  the issue "paused before potential out-of-memory crash" appears. "Resume script execution" just leads to the same issue over and over again. I've tried reinstalling the plug-in but nothing works. I think it's an issue with certain files / the large number of files in my vault, as Scan Vault works fine with my smaller vaults.

![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/50957670/9adcf234-fcac-4e6b-9673-e803885b2620)

**Comment by mw9982** [comment]
I am having this exact issue as well.

**Comment by MisterPresident** [comment]
Fixed this in my pull request.

**Comment by timfarkas** [comment]
Still having this issue with 7k notes on Mac. Interestingly, I didn't have the issue when syncing my vault of similar size on Windows

**Comment by timfarkas** [comment]
bump, still having this issue
